apiVersion: v1
kind: Pod
metadata:
  name: centos
spec:
  containers:
  - image: centos
    command:
    - sleep
    - "3600"
    name: centos
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
  volumes:
  - name: cache-volume
    emptyDir: {}
