apiVersion: v1
kind: Pod
metadata:
  name: mysecret
spec:
  containers:
  - name: mysecret
    image: redis
    volumeMounts:
    - name: foo
      mountPath: "/etc/foo"
      readOnly: true
  volumes:
  - name: foo
    secret:
      secretName: mysecret
