apiVersion: "v1"
kind: Pod
metadata:
  name: nginxpod
spec:
  containers:
    - name: nginx80
      image: nginx
      ports:
        - containerPort: 80
          hostPort: 80
    - name: nginx8800
      image: msfuko/nginx_8800
      ports:
        - containerPort: 8800
          hostPort: 8800
